Repository Arnabjeet/Hacktober-fest-2023, pull requests merged in 2023-10, with the labels that each got.

#2 Fixes issue related to documentation
  README.md
Labels: documentation, hacktoberfest

#4 Added the missing logo ( Fixes #3 )
  README.md
Labels: bug, documentation, hacktoberfest-accepted

#5 Added CONTRIBUTIONS.md
  CONTRIBUTIONS.md
Labels: documentation, hacktoberfest-accepted

#7 Added Queue code in Java
  queue.java
Labels: enhancement, hacktoberfest-accepted

#8 ADDED STACK IN JAVA
  DSA Codes/Java/stack.java
Labels: enhancement, hacktoberfest-accepted

#9 ADDED SINGLE DIMENTIONAL ARRAY
  DSA Codes/Java/singledimensionalarray.java
Labels: enhancement, hacktoberfest-accepted

#10 Added selectionsort
  DSA Codes/Java/selectionsort.java
Labels: enhancement, hacktoberfest-accepted
